sudo: false
language: node_js
node_js:
  - "8.0"
  - "10.0"
  - "node"

addons:
  hosts:
    - nic.localhost
    - tim.localhost
    - nicola.localhost

before_install:
  - npm install -g npm@latest

install:
  - npm ci

script:
  - npm run standard
  - npm run sonar
  - npm run nyc

after_success:
  - snyk monitor

notifications:
  email:
  - solid@janeirodigital.com
  - solid-travis@inrupt.com
